### ISSUE TITLE
Having issues with the example

### ISSUE THREAD

**Issue by juansainz** [nanohard/scribble#2]
Hi I am almost new to GO, but I use to code in other languages, mostly Java and Python. I try to use the example you present in this github but I am having to many issues:
If declare everything outside a func give me an error on db declaration, so I put all the code inside a func. That way the next issue is that Fish is not declared and I try to declare it in many ways without success.

¿ Did you have a complete example that I can copy and paste to a file and run it without issues?

**Comment by nanohard** [comment]
Sorry, I don't have anything at the moment. Usage of the library does assume knowledge of Go. You seem to be missing knowledge of the fundamentals, so I would suggest reading some beginner materials, specifically dealing with scopes and creating types.
